apiVersion: v1
kind: Service
metadata:
  name: ms-configuracion-api
  labels:
    app: ms-configuracion-api
spec:
  selector:
    app: ms-configuracion-api
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP